name: Fmt

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: |
        rustup toolchain install nightly-2020-06-10
        rustup component add rustfmt --toolchain nightly-2020-06-10
    - name: Check formatting
      run: cargo +nightly-2020-06-10 fmt -- --check
    - name: Check no println! usage
      shell: bash
      run: |
        ! grep -rwq ./core -e 'println!'
        ! grep -rwq ./editor -e 'println!'
        ! grep -rwq ./engine -e 'println!'
        ! grep -rwq ./graphics -e 'println!'
        ! grep -rwq ./gui -e 'println!'
