name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: |
        rustup toolchain install nightly-2020-06-10
        rustup component add rustfmt --toolchain nightly-2020-06-10
    - name: Check formatting
      run: cargo +nightly-2020-06-10 fmt -- --check

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master 
        if: matrix.os == 'windows-latest'
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test